# @package _global_

defaults:
  - _self_
  - data: default
  - policy: bc_foundation_dmpel_policy
  - train: default
  - eval: default
  - lifelong: dmpel
  - test: null

seed: 100
folder: null # use default path
bddl_folder: null # use default path
init_states_folder: null # use default path
load_previous_model: false
device: "cuda"
task_embedding_format: "clip"
text_tokens_or_embeddings: "tokens" # "embeddings" # "tokens" # "hidden_states"
task_embedding_one_hot_offset: 1
pretrain: false
pretrain_model_path: ""
benchmark_name: "LIBERO_GOAL"
exp: "debug"
goal_modality: "BUDS"
use_ddp: false
debug_no_eval: false