policy_type: BCFoundationTailPolicy
extra_num_layers: 0
extra_hidden_size: 256
embed_size: 768

transformer_input_size: null
transformer_num_layers: 6
transformer_num_heads: 8
transformer_head_output_size: 96
transformer_mlp_hidden_size: 1024
transformer_dropout: 0.15
transformer_max_seq_len: 10
film_hidden_size: 256

use_lora: 'None' # 'LoRAqkv' or 'None'
fullft: true

defaults:
    - data_augmentation@color_aug: batch_wise_img_color_jitter_group_aug.yaml
    - data_augmentation@translation_aug: translation_aug.yaml
    - data_augmentation@affine_aug: affine_aug.yaml
    - image_encoder: clip_image_encoder_frozen.yaml
    - language_encoder: clip_text_encoder_frozen.yaml
    - position_encoding@temporal_position_encoding: sinusoidal_position_encoding.yaml
    - policy_head: gmm_head.yaml
    - adapter: none.yaml
